#
# Unified Makefile for Handy/SDL Portable Lynx Emulator
#
# by James L. Hammons
#
# This software is licensed under the GPL v2 or any later version. Set the
# file GPL.TXT for details. ;-)
#

# Figure out which system we're compiling for, and set the appropriate variables

OSTYPE=dingux
EXESUFFIX  = .elf

CC			= gcc
CXX			= g++
LD			= g++


TARGET     = handy320

CFLAGS = -DDINGUX -O2 -g3 -DWANT_CRC32 -DANSI_GCC -DSDL_PATCH -DOSS_OUTPUT
CXXFLAGS = $(CFLAGS)
LDFLAGS =
LIBS = -lstdc++ -lSDL -lz -lpthread 

INCS = -I./src -I./src/handy-libretro -I./src/sdlemu

OBJS = \
		obj/cart.o \
		obj/memmap.o \
		obj/eeprom.o \
		obj/lynxdec.o \
		obj/mikie.o \
		obj/ram.o \
		obj/rom.o \
		obj/susie.o \
		obj/system.o \
		obj/unzip.o \
		obj/sdlemu_filter.o \
		obj/handy_sdl_main.o \
		obj/handy_sdl_handling.o \
		obj/handy_sdl_graphics.o \
		obj/handy_sdl_sound.o \
		obj/gui.o \
		obj/font.o

all: obj $(TARGET)$(EXESUFFIX)
	@echo "*** Looks like it compiled OK... Give it a whirl!"

clean:
	@echo -n "*** Cleaning out the garbage..."
	@rm -rf obj
	@rm -f ./$(TARGET)$(EXESUFFIX)
	@echo done!

obj:
	@mkdir obj

obj/%.o: src/gui/%.cpp
	@echo "*** Compiling $<..."
	$(CXX) $(CXXFLAGS) $(INCS) -c $< -o $@

obj/%.o: src/handy-libretro/%.cpp
	@echo "*** Compiling $<..."
	$(CXX) $(CXXFLAGS) $(INCS) -c $< -o $@

obj/%.o: src/%.c
	@echo "*** Compiling $<..."
	$(CC) $(CFLAGS) $(INCS) -c $< -o $@

obj/%.o: src/%.cpp
	@echo "*** Compiling $<..."
	$(CXX) $(CXXFLAGS) $(INCS) -c $< -o $@

obj/%.o: src/sdlemu/%.c
	@echo "*** Compiling $<..."
	$(CC) $(CFLAGS) $(INCS) -c $< -o $@

obj/%.o: src/sdlemu/%.cpp
	@echo "*** Compiling $<..."
	$(CXX) $(CXXFLAGS) $(INCS) -c $< -o $@

obj/%.o: src/unzip/%.c
	@echo "*** Compiling $<..."
	$(CC) $(CFLAGS) $(INCS) -c $< -o $@
	
$(TARGET)$(EXESUFFIX): $(OBJS)
	@echo "*** Linking it all together..."
	$(LD) $(LDFLAGS) -o $@ $(OBJS) $(LIBS)

# Pull in dependencies autogenerated by gcc's -MMD switch
# The "-" in front is there just in case they haven't been created yet

-include obj/*.d

