#!/bin/sh

mkdir -p ipkg/home/retrofw/emus/handy
mkdir -p ipkg/home/retrofw/apps/gmenu2x/sections/emulators
cp handy ipkg/home/retrofw/emus/handy/handy
cp handy.png ipkg/home/retrofw/emus/handy/handy.png

cd ipkg

# https://unix.stackexchange.com/questions/219268/how-to-add-new-lines-when-using-echo
print()
	case    ${IFS- } in
	(\ *)   printf  %b\\n "$*";;
	(*)     IFS=\ $IFS
	printf  %b\\n "$*"
	IFS=${IFS#?}
esac

# Create GmenuNx entry file plus other things

print 'Package: handy
Version: 20190219
Description: Atari Lynx emulator
Section: emus
Priority: optional
Maintainer: gameblabla
Architecture: mipsel
Homepage: https://github.com/gameblabla/handy
Depends:
Source: https://github.com/gameblabla/handy' > control

print '2.0' > debian-binary

print 'title=Handy
description=Atari Lynx Emulator
exec=/home/retrofw/emus/handy/handy
clock=600
selectordir=/home/retrofw/roms
selectorfilter=.lnx,.bin,.zip
' > home/retrofw/apps/gmenu2x/sections/emulators/handy

tar -czvf control.tar.gz control
tar -czvf data.tar.gz home
ar rv ../handy.ipk control.tar.gz data.tar.gz debian-binary

cd ..
rm -r ipkg
